# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2019-04-28 04:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='description',
            field=models.CharField(default='Sample Description', max_length=64),
            preserve_default=False,
        ),
    ]
